import "./admin-user";
import "./profile-edit-profile";
import "./profile-edit-password";
import "./user";
import "./cipher-key";
import "./location";
import "./cipher-type";
import "./key-type";
import "./cipher-key-similarity";
import "./tag";
import "./cryptogram";
import "./solution";
import "./person";
import "./language";
import "./category";
import './digitalized-transcription';
import './logs'
